name: Prettier code formatter

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4

      - name: Install Prettier 💾
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid

      - name: Prettier Format & Write ✍️
        run: npx prettier . --write

      - name: Commit formatted files 🚀
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-fix formatting with Prettier"
